# This is a basic workflow to help you get started with Actions

name: Build application

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
      - 'src/**'
      - 'static/**'
      - '!static/favicon.ico'
      - '!static/rekidai.json'
      - '!static/rekidai.min.json'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: write-all

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - run: |
          git config --local user.email "workflow@example.com"
          git config --local user.name "workflow"
          git pull
          cp -f src/routes/index.svelte index.svelte.bak
          cp -f src/routes/callback.svelte callback.svelte.bak
          sed -i "s/^\s*//" src/routes/index.svelte
          sed -i "s/^\s*//" src/routes/callback.svelte
          npm install
          npm run build
          rm -rf app && mv -f build/*.html build/*.js build/*.ico build/*.json build/app . && rm -rf build && rm -f table-sort.js rekidai.json
          mv -f index.svelte.bak src/routes/index.svelte
          mv -f callback.svelte.bak src/routes/callback.svelte
          git add .
          git commit -m "Automatically updated by Workflow Action"
          git push origin main

      # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!

      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
